version: "3"

services:
  jarvis_redis:
    image: hypriot/rpi-redis:latest
  jarvis-app:
    image: busbyjon/jarvis:arm
    ports:
      - "3000":"3000"
  jarvis-worker:
    image: busbyjon/jarvis:arm




