version: "3"

services:
  jarvis_redis:
    image: hypriot/rpi-redis:latest
    ports:
      - "6379"
    networks:
      - jarvisapp
    deploy:
      placement:
        constraints: [node.role == manager]
  jarvis-app:
    image: busbyjon/jarvis:arm
    ports:
      - "3000:3000"
    networks:
      - jarvisapp
    depends_on:
      - jarvis_redis
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=JARVIS]
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
        # placement constraint - in this case on 'worker' nodes only
    env_file: ../secrets.env
  jarvis-worker:
    image: busbyjon/jarvis:arm
    command: bundle exec sidekiq
    networks:
      jarvisapp:
        aliases:
          - workers
    depends_on:
      - jarvis_redis
    # service deployment
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=JARVIS]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      # placement constraint - in this case on 'worker' nodes only
      placement:
        constraints: [node.role == worker]
    env_file: ../secrets.env

networks:
    jarvisapp:
