:schedule:
  GetTadoDataJob:
    every: 1m   # Runs once per minute
    class: GetTadoDataJob
  MorningLightsWeekday:
    cron: "0 5 * * 1-5 Europe/London"
    class: SetLightsJob
    args: [ morningOn, "Morning Lights On"] 
  BedtimeLightsWeekday:
    cron: "15 22 * * 1-5 Europe/London"
    class: SetLightsJob
    args: [ bedtimeOn, "Bedtime Lights On"]
  BedtimeLightsWeekend:
    cron: "30 22 * * 0,6 Europe/London"
    class: SetLightsJob
    args: [ bedtimeOn, "Bedtime Lights On"]
  AllLightsOff:
    cron: "55 22 * * * Europe/London"
    class: SetLightsJob
    args: [bedtimeOff, "All Lights Off"]
  MorningLightsWeekend:
    cron: "0 7 * * 0,6 Europe/London"
    class: SetLightsJob
    args: [morningOn, "Morning Lights On"]
  SetSunTimesJob:
    cron: "10 3 * * * Europe/London"
    class: SetSunTimesJob


